-- MySQL Script generated by MySQL Workbench
-- Wed Jul 24 17:53:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gtecblog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gtecblog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gtecblog` ;
USE `gtecblog` ;

-- -----------------------------------------------------
-- Table `gtecblog`.`user_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtecblog`.`user_types` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtecblog`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtecblog`.`users` (
  `id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `is_active` TINYINT NULL,
  `email` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_users_user_types2_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_user_types`
    FOREIGN KEY (`type_id`)
    REFERENCES `gtecblog`.`user_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtecblog`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtecblog`.`posts` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `slug` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `image_path` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `author_id_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `fk_posts_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gtecblog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtecblog`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtecblog`.`tags` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtecblog`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtecblog`.`profile` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `picture_path` VARCHAR(255) NULL,
  `bio` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profile_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_profile_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `gtecblog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtecblog`.`posts_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtecblog`.`posts_tags` (
  `post_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  INDEX `fk_posts_tags_tags1_idx` (`tags_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_tags_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `gtecblog`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `gtecblog`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gtecblog`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gtecblog`.`comments` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `parent_id` INT NULL,
  `content` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_posts1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_comments_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comments_comments1_idx` (`parent_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `gtecblog`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `gtecblog`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_comments1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `gtecblog`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
